# Generated by Django 3.2 on 2025-01-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_taluk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_villages', to='properties.taluk')),
            ],
        ),
    ]
