# Generated by Django 3.2 on 2025-01-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_revenuevillage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('survey_no', models.CharField(max_length=100)),
                ('subdivision', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('facing', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.district')),
                ('revenue_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.revenuevillage')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.state')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.taluk')),
            ],
        ),
    ]
