# Generated by Django 3.2 on 2025-01-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='properties.district'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='revenue_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='properties.revenuevillage'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='properties.state'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='properties.taluk'),
        ),
    ]
