# Generated by Django 3.2 on 2025-01-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20250118_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='land_image',
            field=models.ImageField(blank=True, null=True, upload_to='land_images/'),
        ),
    ]
