# Generated by Django 3.2 on 2025-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_plot_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='price_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
