# Generated by Django 3.2 on 2025-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_plot_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='price_range',
            field=models.CharField(max_length=100),
        ),
    ]
