# Generated by Django 3.2 on 2025-01-18 10:38

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'plot')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
