# Generated by Django 3.2 on 2025-01-18 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20250118_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='plots',
        ),
        migrations.AddField(
            model_name='cart',
            name='datetimeexit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='plot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.plot'),
        ),
    ]
