# Generated by Django 3.2 on 2025-01-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
