# Generated by Django 3.2 on 2025-01-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
